#!/usr/bin/bash

filename=
interface=

function usage() {
	echo $0 -i interface -f filename
	exit 1
}

function extract_params() {
	if [ $# -ne 4 ]
	then
		usage
	fi

	while [ $# -gt 1 ]
	do
		case $1 in
			-f)
				filename=$2
				;;
			-i)
				interface=$2
				;;
			*)
				usage
				;;
		esac
		shift
		shift
	done
}

extract_params $@

DATE=`date +"%Y-%m-%d %H:%M"`

data_string=`cat /proc/net/dev | grep -w $interface | cut -f 2 -d ':' | awk '{print $1,$2,$9,$10}'`

if [ -z "$data_string" ]
then
	echo Interface $interface does not exist
fi

rx_bytes=`echo $data_string | awk '{print $1}'`
rx_pkts=`echo $data_string | awk '{print $2}'`
tx_bytes=`echo $data_string | awk '{print $3}'`
tx_pkts=`echo $data_string | awk '{print $4}'`

if [ ! -e $filename ]
then
	echo "Date,RX bytes,RX packets,Avg RX Pkt,TX bytes,TX packets,Avg TX Pkt" > $filename
fi

echo $DATE,$rx_bytes,$rx_pkts,$(($rx_bytes/$rx_pkts)),$tx_bytes,$tx_pkts,$(($tx_bytes/$tx_pkts)) >> $filename
